# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'musicplayer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtGui import QCursor
from PyQt5.QtWidgets import QMenu, QAction
import time
import os
from PyQt5 import QtCore, QtGui, QtWidgets
from sound import Play
import cover


class BackEnd():
    def __init__(self):
        self.music = Play()
        self.musicAddresses = []  # contains file addresses
        self.musicFiles = []  # contains file names
        self.musicIndex = 0
        self.cover = "resources/cover3.png"
        self.repeating = "all"
        self.ended = False
        self.currentTime = 0
        self.sliderPressed = False
        self.gotoPosition = 0

    def addMusicNames(self):
        if len(self.musicFiles) > 0:
            for index, song in enumerate(self.musicAddresses):
                self.music.get_metadata(song)
                if self.music.title == "None":
                    title = self.musicFiles[self.musicIndex]
                else:
                    title = self.music.title
                ui.add_music(title, index)

    def updateText(self):
        if len(self.musicAddresses) > 0:
            self.music.get_metadata(self.musicAddresses[self.musicIndex])
        if self.music.title != "None":
            title = self.music.title
        else:
            title = self.musicFiles[self.musicIndex]
        ui.labelTitle.setText(
            f"<span style='font-size:14pt;font-weight:300;'>{title}</span>\
                <span style='color:#595959;'>{self.music.artist}</span>")
        # <span style='font-size:14pt; font-weight:600; color:#ff0000;'>Hello</span>

    def setIconPlay(self, icon):
        iconMap = QtGui.QIcon()
        iconMap.addPixmap(QtGui.QPixmap(icon),
                          QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ui.buttonPlay.setIcon(iconMap)
        ui.buttonPlay.setIconSize(QtCore.QSize(40, 40))

    def setIconRepeat(self, icon):
        iconMap = QtGui.QIcon()
        iconMap.addPixmap(QtGui.QPixmap(icon),
                          QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ui.buttonRepeat.setIcon(iconMap)
        ui.buttonRepeat.setIconSize(QtCore.QSize(25, 25))

    def movedSlider(self, value):
        if self.sliderPressed:
            self.gotoPosition = int((value/100)*self.music.duration)
            self.currentTime = self.music.elapsed_time

    def pressedSlider(self):
        self.sliderPressed = True

    def releasedSlider(self):
        self.sliderPressed = False
        self.music.goto(self.gotoPosition)
        self.currentTime = self.music.elapsed_time

    def clickName(self, index):
        self.musicIndex = index
        self.play_music(audio_file=self.musicAddresses[self.musicIndex])

    def clickFile(self):
        fileDialog = QtWidgets.QFileDialog()
        address = fileDialog.getExistingDirectory(MainWindow, "import music")
        self.musicAddresses = []
        self.musicIndex = 0
        self.musicFiles = []
        try:
            files = os.listdir(address)
        except FileNotFoundError:
            None
        else:

            for item in files:
                if ('.' in item) and (item.split('.')):
                    exten = item.split('.')[-1]
                else:
                    exten = None

                if exten in ["mp3", "wav"]:
                    self.musicFiles.append(item)
                    self.musicAddresses.append(address+"/"+item)
        print(self.musicFiles)

        # music found; calling function
        if len(self.musicFiles) >= 1:
            print("music found, calling function")
            self.play_music(audio_file=self.musicAddresses[self.musicIndex])
            self.addMusicNames()

        else:
            print('no music found')

    def clickRepeat(self):
        list = ["all", "one", "none"]
        indx = list.index(self.repeating)
        indx += 1
        if indx == 3:
            indx = 0
        self.repeating = list[indx]
        self.setIconRepeat(f"resources/repeat_{self.repeating}.png")
        # print(f"resources/repeat_{self.repeating}.png")

    def clickNext(self):
        if self.musicIndex < len(self.musicAddresses)-1:
            self.musicIndex += 1
        else:
            self.musicIndex = 0

        try:
            self.play_music(audio_file=self.musicAddresses[self.musicIndex])
            self.updateText()
        except IndexError:
            None
        self.currentTime = 0

    def clickPrev(self):
        if self.musicIndex > 0:
            self.musicIndex -= 1
        else:
            self.musicIndex = len(self.musicAddresses)-1
        try:
            self.play_music(audio_file=self.musicAddresses[self.musicIndex])
            self.updateText()
        except IndexError:
            None
        self.currentTime = 0

    def clickPlay(self):
        if self.music.isPlaying is True:
            self.pause_music()
        elif len(self.musicAddresses) == 0:
            self.clickFile()
        else:
            self.resume_music()

    def clickVolume(self):
        if not ui.hasVolumeSlider:
            ui.popupSlider()
            ui.hasVolumeSlider = True
        else:
            ui.delPopupSlider()

    def clickBack(self):
        if ui.currentMode == "player":
            ui.setupUiMenu(MainWindow)
            ui.currentMode = "menu"
            self.updateText()
            self.addMusicNames()
            try:
                self.setCover(self.musicAddresses[self.musicIndex])
            except IndexError:
                None
        else:
            ui.currentMode = "player"

    def clickImage(self):
        if ui.currentMode == "player":
            ui.currentMode = "menu"
        else:
            ui.setupUi(MainWindow)
            ui.currentMode = "player"
            self.addMusicNames()
            self.updateText()
            try:
                self.setCover(self.musicAddresses[self.musicIndex])
            except IndexError:
                None

    def play_music(self, audio_file):
        self.music.play_audio(audio_file, 0)
        self.music.elapsed_time = 0
        self.updateText()
        self.setIconPlay("resources/pause.png")
        self.setCover(audio_file)
        self.currentTime = -1
        self.ended = False

    def pause_music(self):
        self.setIconPlay("resources/play.png")
        self.music.pause_audio()
        self.currentTime = self.music.elapsed_time

    def resume_music(self):
        print("audio_file", self.music.audio_file)
        self.setIconPlay("resources/pause.png")
        self.music.resume_audio()
        self.startTime = time.time()

    def setCover(self, address):

        bytes_data = cover.extract(address)
        # Create a QImage from the bytes data
        qimage = QtGui.QImage.fromData(bytes_data)
        # Create a QPixmap from the QImage
        pixmap = QtGui.QPixmap.fromImage(qimage)
        if ui.currentMode == "player":
            ui.labelImage.setPixmap(pixmap)
        else:
            icon = QtGui.QIcon()
            icon.addPixmap(pixmap)
            ui.buttonImage.setIcon(icon)

    def convert_to_mins(self, timeInSeconds):
        mins = int((timeInSeconds)//60)
        secs = int((timeInSeconds) % 60)
        return f"{mins}:{secs}"

    def periodic_function(self):
        if self.music.isPlaying is True:
            self.currentTime += 1

        if (self.currentTime) > self.music.duration:
            self.ended = True

        ui.labelTime.setText(self.convert_to_mins(
            self.currentTime) + '/'+self.convert_to_mins(self.music.duration))

        if self.ended:
            self.currentTime = 0
            if self.repeating == "all":
                self.clickNext()
            elif self.repeating == "one":
                self.play_music(
                    audio_file=self.musicAddresses[self.musicIndex])
            else:
                if self.musicIndex >= len(self.musicFiles)-1:
                    None
                else:
                    self.clickNext()

        if self.music.duration != 0:
            percentage = int((self.currentTime/self.music.duration)*100)
            if not backend.sliderPressed:
                ui.horizontalSlider.setProperty("value", percentage)


class Ui_MainWindow(object):
    def __init__(self) -> None:
        self.hasVolumeSlider = False
        self.currentMode = "player"

    def setStyle(self, name):
        eval(name).setStyleSheet("background-color:white; border-radius:25px")

        if name == "self.horizontalSlider":
            eval(name).setStyleSheet("QSlider::groove:horizontal {"
                                     "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #16113d, stop:1 #a5419e);"
                                     "border: 1px solid #999999;"
                                     "height: 6px;"
                                     "margin: 2px 0;"
                                     "}"
                                     "QSlider::handle:horizontal {"
                                     "background: white;"
                                     "border: 1px solid black;"
                                     "width: 15px;"
                                     "height: 15px;"
                                     "margin: -1px 0;"
                                     "border-radius: 25px;"
                                     "}"
                                     "QSlider::handle:horizontal:active {"
                                     "background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 white, stop:1 white);"
                                     "}")

    def assignKeys(self):
        self.buttonBack.clicked.connect(backend.clickBack)
        self.buttonFile.clicked.connect(backend.clickFile)
        self.buttonRepeat.clicked.connect(backend.clickRepeat)
        self.buttonPrev.clicked.connect(backend.clickPrev)
        self.buttonPlay.clicked.connect(backend.clickPlay)
        self.buttonNext.clicked.connect(backend.clickNext)
        self.buttonVol.clicked.connect(backend.clickVolume)
        self.horizontalSlider.sliderPressed.connect(backend.pressedSlider)
        self.horizontalSlider.sliderReleased.connect(backend.releasedSlider)
        self.horizontalSlider.valueChanged.connect(backend.movedSlider)
        self.setStyle("self.buttonBack")
        self.setStyle("self.buttonFile")
        self.setStyle("self.buttonSettings")
        self.setStyle("self.horizontalSlider")
        self.setStyle("self.buttonRepeat")
        self.setStyle("self.buttonPrev")
        self.setStyle("self.buttonPlay")
        self.setStyle("self.buttonNext")
        self.setStyle("self.buttonVol")

    def add_music(self, name, index):
        if self.currentMode == "player":
            return
        self.musicName = QtWidgets.QPushButton(self.frame)
        self.musicName.setText(str(name))
        self.musicName.clicked.connect(lambda: backend.clickName(index))
        self.verticalLayout_2.addWidget(self.musicName)
        self.musicName.setStyleSheet(
            "font-size:14pt;text-align:left;background-color:white; border-radius:25px")

    def setupUiMenu(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(324, 436)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(11, -1, 0, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.buttonFile = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.buttonFile.sizePolicy().hasHeightForWidth())
        self.buttonFile.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/folder.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonFile.setIcon(icon)
        self.buttonFile.setIconSize(QtCore.QSize(20, 20))
        self.buttonFile.setObjectName("buttonFile")
        self.horizontalLayout_4.addWidget(self.buttonFile)
        self.buttonSettings = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.buttonSettings.sizePolicy().hasHeightForWidth())
        self.buttonSettings.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/settings.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSettings.setIcon(icon1)
        self.buttonSettings.setObjectName("buttonSettings")
        self.horizontalLayout_4.addWidget(self.buttonSettings)
        self.verticalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout.addWidget(self.frame, 0, QtCore.Qt.AlignTop)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.buttonImage = QtWidgets.QPushButton(self.frame_5)
        self.buttonImage.setMaximumSize(QtCore.QSize(80, 80))
        self.buttonImage.setText("")
        self.icon2 = QtGui.QIcon()
        self.icon2.addPixmap(QtGui.QPixmap("resources/cover3.png"),
                             QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonImage.setIcon(self.icon2)
        self.buttonImage.setIconSize(QtCore.QSize(80, 80))
        self.buttonImage.setObjectName("buttonImage")
        self.horizontalLayout_3.addWidget(self.buttonImage)
        self.labelTitle = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelTitle.sizePolicy().hasHeightForWidth())
        self.labelTitle.setSizePolicy(sizePolicy)
        self.labelTitle.setScaledContents(False)
        self.labelTitle.setWordWrap(False)
        self.labelTitle.setObjectName("labelTitle")
        self.horizontalLayout_3.addWidget(self.labelTitle)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(11, 11, 10, -1)
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalSlider = QtWidgets.QSlider(self.frame_3)
        self.horizontalSlider.setProperty("value", 69)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_2.addWidget(self.horizontalSlider)
        self.labelTime = QtWidgets.QLabel(self.frame_3)
        self.labelTime.setMinimumSize(QtCore.QSize(0, 0))
        self.labelTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelTime.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.labelTime.setObjectName("labelTime")
        self.horizontalLayout_2.addWidget(self.labelTime)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonRepeat = QtWidgets.QPushButton(self.frame_2)
        self.buttonRepeat.setMinimumSize(QtCore.QSize(0, 40))
        self.buttonRepeat.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/repeat_all.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRepeat.setIcon(icon3)
        self.buttonRepeat.setIconSize(QtCore.QSize(25, 25))
        self.buttonRepeat.setObjectName("buttonRepeat")
        self.horizontalLayout.addWidget(
            self.buttonRepeat, 0, QtCore.Qt.AlignLeft)
        self.buttonPrev = QtWidgets.QPushButton(self.frame_2)
        self.buttonPrev.setMinimumSize(QtCore.QSize(0, 50))
        self.buttonPrev.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resources/Back.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonPrev.setIcon(icon4)
        self.buttonPrev.setIconSize(QtCore.QSize(40, 40))
        self.buttonPrev.setObjectName("buttonPrev")
        self.horizontalLayout.addWidget(
            self.buttonPrev, 0, QtCore.Qt.AlignRight)
        self.buttonPlay = QtWidgets.QPushButton(self.frame_2)
        self.buttonPlay.setMinimumSize(QtCore.QSize(0, 50))
        self.buttonPlay.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resources/play.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonPlay.setIcon(icon5)
        self.buttonPlay.setIconSize(QtCore.QSize(40, 40))
        self.buttonPlay.setObjectName("buttonPlay")
        self.horizontalLayout.addWidget(
            self.buttonPlay, 0, QtCore.Qt.AlignHCenter)
        self.buttonNext = QtWidgets.QPushButton(self.frame_2)
        self.buttonNext.setMinimumSize(QtCore.QSize(0, 50))
        self.buttonNext.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resources/next.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonNext.setIcon(icon6)
        self.buttonNext.setIconSize(QtCore.QSize(40, 40))
        self.buttonNext.setObjectName("buttonNext")
        self.horizontalLayout.addWidget(
            self.buttonNext, 0, QtCore.Qt.AlignLeft)
        self.buttonVol = QtWidgets.QPushButton(self.frame_2)
        self.buttonVol.setMinimumSize(QtCore.QSize(0, 40))
        self.buttonVol.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(
            "resources/speaker-filled-audio-tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonVol.setIcon(icon7)
        self.buttonVol.setIconSize(QtCore.QSize(25, 25))
        self.buttonVol.setObjectName("buttonVol")
        self.horizontalLayout.addWidget(
            self.buttonVol, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.buttonImage.clicked.connect(backend.clickImage)
        self.assignKeys()
        self.add_music("Your song List", 0)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(448, 683)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_4.setContentsMargins(11, -1, 0, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.buttonBack = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.buttonBack.sizePolicy().hasHeightForWidth())
        self.buttonBack.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/left.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonBack.setIcon(icon)
        self.buttonBack.setObjectName("buttonBack")
        self.horizontalLayout_4.addWidget(self.buttonBack)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.buttonFile = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.buttonFile.sizePolicy().hasHeightForWidth())
        self.buttonFile.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("resources/folder.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonFile.setIcon(icon1)
        self.buttonFile.setIconSize(QtCore.QSize(20, 20))
        self.buttonFile.setObjectName("buttonFile")
        self.horizontalLayout_4.addWidget(self.buttonFile)
        self.buttonSettings = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.buttonSettings.sizePolicy().hasHeightForWidth())
        self.buttonSettings.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("resources/settings.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSettings.setIcon(icon2)
        self.buttonSettings.setObjectName("buttonSettings")
        self.horizontalLayout_4.addWidget(self.buttonSettings)
        self.verticalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.labelImage = QtWidgets.QLabel(self.frame)
        self.labelImage.setMaximumSize(QtCore.QSize(400, 400))
        self.labelImage.setText("")
        self.labelImage.setPixmap(QtGui.QPixmap("resources/cover3.png"))
        self.labelImage.setScaledContents(True)
        self.labelImage.setObjectName("labelImage")
        self.horizontalLayout_5.addWidget(self.labelImage)
        self.verticalLayout.addWidget(self.frame)
        self.frame_5 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelTitle = QtWidgets.QLabel(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.labelTitle.sizePolicy().hasHeightForWidth())
        self.labelTitle.setSizePolicy(sizePolicy)
        self.labelTitle.setScaledContents(False)
        self.labelTitle.setWordWrap(False)
        self.labelTitle.setObjectName("labelTitle")
        self.horizontalLayout_3.addWidget(self.labelTitle)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(11, 11, 10, -1)
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalSlider = QtWidgets.QSlider(self.frame_3)
        self.horizontalSlider.setProperty("value", 69)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_2.addWidget(self.horizontalSlider)
        self.labelTime = QtWidgets.QLabel(self.frame_3)
        self.labelTime.setMinimumSize(QtCore.QSize(0, 0))
        self.labelTime.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.labelTime.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.labelTime.setObjectName("labelTime")
        self.horizontalLayout_2.addWidget(self.labelTime)
        self.verticalLayout.addWidget(self.frame_3)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(300, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonRepeat = QtWidgets.QPushButton(self.frame_2)
        self.buttonRepeat.setMinimumSize(QtCore.QSize(0, 40))
        self.buttonRepeat.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("resources/repeat_all.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonRepeat.setIcon(icon3)
        self.buttonRepeat.setIconSize(QtCore.QSize(25, 25))
        self.buttonRepeat.setObjectName("buttonRepeat")
        self.horizontalLayout.addWidget(
            self.buttonRepeat, 0, QtCore.Qt.AlignLeft)
        self.buttonPrev = QtWidgets.QPushButton(self.frame_2)
        self.buttonPrev.setMinimumSize(QtCore.QSize(0, 50))
        self.buttonPrev.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("resources/Back.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonPrev.setIcon(icon4)
        self.buttonPrev.setIconSize(QtCore.QSize(40, 40))
        self.buttonPrev.setObjectName("buttonPrev")
        self.horizontalLayout.addWidget(
            self.buttonPrev, 0, QtCore.Qt.AlignRight)
        self.buttonPlay = QtWidgets.QPushButton(self.frame_2)
        self.buttonPlay.setMinimumSize(QtCore.QSize(0, 50))
        self.buttonPlay.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("resources/play.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonPlay.setIcon(icon5)
        self.buttonPlay.setIconSize(QtCore.QSize(40, 40))
        self.buttonPlay.setObjectName("buttonPlay")
        self.horizontalLayout.addWidget(
            self.buttonPlay, 0, QtCore.Qt.AlignHCenter)
        self.buttonNext = QtWidgets.QPushButton(self.frame_2)
        self.buttonNext.setMinimumSize(QtCore.QSize(0, 50))
        self.buttonNext.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("resources/next.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonNext.setIcon(icon6)
        self.buttonNext.setIconSize(QtCore.QSize(40, 40))
        self.buttonNext.setObjectName("buttonNext")
        self.horizontalLayout.addWidget(
            self.buttonNext, 0, QtCore.Qt.AlignLeft)
        self.buttonVol = QtWidgets.QPushButton(self.frame_2)
        self.buttonVol.setMinimumSize(QtCore.QSize(0, 40))
        self.buttonVol.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(
            "resources/speaker-filled-audio-tool.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonVol.setIcon(icon7)
        self.buttonVol.setIconSize(QtCore.QSize(25, 25))
        self.buttonVol.setObjectName("buttonVol")
        self.horizontalLayout.addWidget(
            self.buttonVol, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.frame_2)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.assignKeys()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.buttonBack.setText(_translate("MainWindow", "Back"))
        self.buttonFile.setText(_translate("MainWindow", "File"))
        self.buttonSettings.setText(_translate("MainWindow", "Settings"))
        self.labelTitle.setText(_translate(
            "MainWindow", "press File to import music"))

    def popupSlider(self):
        self.volumeSlider = QtWidgets.QSlider(MainWindow)
        print("Volume slider added")
        self.volumeSlider.setProperty("value", 69)
        x = ui.buttonVol.pos().x()+20
        y = MainWindow.height()-200
        print(x, y)
        self.volumeSlider.setGeometry(x, y, 20, 100)
        self.volumeSlider.setOrientation(QtCore.Qt.Vertical)
        self.volumeSlider.setObjectName("volumeSlider")
        self.volumeSlider.show()

    def delPopupSlider(self):
        if ui.hasVolumeSlider:
            self.volumeSlider.setParent(None)
            self.volumeSlider.deleteLater()
            ui.hasVolumeSlider = False


class MainWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.move(1000, 100)  # Initial size
        self.setWindowTitle("Music")
        self.setStyleSheet("background-color:#ffffff;")
        windowIcon = QtGui.QIcon()
        windowIcon.addPixmap(QtGui.QPixmap("resources/sound-waves.png"))
        self.setWindowIcon(windowIcon)

        # Call periodic function #
        self.timer = QtCore.QTimer()
        self.timer.timeout.connect(backend.periodic_function)
        self.timer.start(1000)  # Update every second

        self.stacked_widget = QtWidgets.QStackedWidget()
        self.main_menu_widget = QtWidgets.QWidget()
        self.stacked_widget.addWidget(self.main_menu_widget)

    def resizeEvent(self, event):
        if ui.currentMode == "player":
            pass
        else:
            return
        # Get the new width and height
        resize_factor = 2
        imageDim = int(self.height()/resize_factor)
        if self.height() >= 900 and self.width() >= 1800:
            ui.labelImage.setMaximumSize(700, 700)
        else:
            ui.labelImage.setMaximumSize(imageDim, imageDim)
        ui.delPopupSlider()

    def mousePressEvent(self, event) -> None:
        if event.button() == QtCore.Qt.LeftButton:
            ui.delPopupSlider()


#
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    backend = BackEnd()
    MainWindow = MainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
